import { Category, AuthorStyle, HindiAuthorStyle, NarratorStyle, Language } from './types';

export const CATEGORIES: Category[] = [
  { id: 'science', label: 'Science & Innovation', icon: 'Atom', color: 'bg-blue-100 text-blue-600', description: 'Explorers of the universe and inventors of new things.' },
  { id: 'social', label: 'Social Reform & Service', icon: 'Heart', color: 'bg-red-100 text-red-600', description: 'Heroes who fought for justice, peace, and helping others.' },
  { id: 'sports', label: 'Sports & Adventure', icon: 'Trophy', color: 'bg-yellow-100 text-yellow-600', description: 'Champions of strength, courage, and breaking limits.' },
  { id: 'arts', label: 'Art, Literature & Music', icon: 'Music', color: 'bg-purple-100 text-purple-600', description: 'Creators of beauty, stories, and songs that touch the soul.' },
  { id: 'environment', label: 'Environment & Nature', icon: 'Leaf', color: 'bg-green-100 text-green-600', description: 'Guardians of our planet, animals, and forests.' },
  { id: 'philosophy', label: 'Philosophy & Wisdom', icon: 'BookOpen', color: 'bg-indigo-100 text-indigo-600', description: 'Thinkers who taught us how to live better lives.' },
  { id: 'leadership', label: 'Leadership & Politics', icon: 'Globe', color: 'bg-orange-100 text-orange-600', description: 'Leaders who guided nations and people through dark times.' },
  { id: 'education', label: 'Education & Teaching', icon: 'User', color: 'bg-pink-100 text-pink-600', description: 'Teachers who opened minds and built futures.' },
];

export const SCIENCE_CATEGORIES: Category[] = [
  { id: 'physics', label: 'Physics & Energy', icon: 'Zap', color: 'bg-emerald-100 text-emerald-600', description: 'Forces, motion, light, and the laws of the universe.' },
  { id: 'chemistry', label: 'Chemistry & Matter', icon: 'FlaskConical', color: 'bg-teal-100 text-teal-600', description: 'Elements, reactions, and the building blocks of everything.' },
  { id: 'biology', label: 'Biology & Life', icon: 'Dna', color: 'bg-lime-100 text-lime-600', description: 'Cells, evolution, plants, and the secrets of life.' },
  { id: 'space', label: 'Astronomy & Space', icon: 'Rocket', color: 'bg-indigo-100 text-indigo-600', description: 'Stars, planets, black holes, and the cosmos.' },
  { id: 'tech', label: 'Tech & Computing', icon: 'Cpu', color: 'bg-cyan-100 text-cyan-600', description: 'Computers, AI, internet, and digital inventions.' },
  { id: 'earth', label: 'Earth & Environment', icon: 'Globe', color: 'bg-green-100 text-green-600', description: 'Geology, weather, oceans, and climate.' },
];

export const PHILOSOPHY_CATEGORIES: Category[] = [
  { id: 'ethics', label: 'Ethics & Morality', icon: 'Scale', color: 'bg-violet-100 text-violet-600', description: 'Questions about right, wrong, and justice.' },
  { id: 'governance', label: 'Society & Governance', icon: 'Landmark', color: 'bg-fuchsia-100 text-fuchsia-600', description: 'Democracy, laws, and how we live together.' },
  { id: 'metaphysics', label: 'Reality & Existence', icon: 'Brain', color: 'bg-purple-100 text-purple-600', description: 'What is real? What is the mind? The big questions.' },
  { id: 'eastern', label: 'Eastern Wisdom', icon: 'Lotus', color: 'bg-orange-100 text-orange-600', description: 'Ideas from India, China, and Japan about harmony and life.' },
  { id: 'western', label: 'Western Thought', icon: 'Pillar', color: 'bg-blue-100 text-blue-600', description: 'Logic, reason, and ideas from Greece to modern Europe.' },
  { id: 'religion', label: 'World Religions', icon: 'BookHeart', color: 'bg-rose-100 text-rose-600', description: 'History and core values of major faiths (neutral perspective).' },
];

export const AUTHOR_STYLES: AuthorStyle[] = [
  {
    id: 'rabindranath_tagore',
    name: 'Rabindranath Tagore',
    description: 'Poetic, lyrical prose with deep spiritual undertones',
    persona: 'The Poet-Philosopher',
    era: '1861–1941',
    majorWorks: ['Gitanjali', 'The Home and the World', 'Gora'],
    voiceCharacteristics: ['lyrical sentences', 'nature metaphors', 'inner spiritual journey', 'gentle wisdom'],
    avoidances: ['harsh technical language', 'cynicism', 'abrupt scene cuts'],
    sampleTone: 'Like morning light on still water — serene, luminous, searching.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'ruskin_bond',
    name: 'Ruskin Bond',
    description: 'Warm, conversational, Himalayan simplicity',
    persona: 'The Gentle Observer',
    era: '1934–present',
    majorWorks: ['The Room on the Roof', 'A Flight of Pigeons', 'The Blue Umbrella'],
    voiceCharacteristics: ['short clear sentences', 'vivid sensory detail', 'quiet wonder', 'warmth for ordinary people'],
    avoidances: ['grandiloquence', 'tragedy without hope', 'complex flashback structures'],
    sampleTone: 'Sitting beside a hill stream, watching clouds — unhurried, affectionate, alive.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'roald_dahl',
    name: 'Roald Dahl',
    description: 'Mischievous wit, child-eye view, delicious darkness',
    persona: 'The Mischief-Maker',
    era: '1916–1990',
    majorWorks: ['Matilda', 'Charlie and the Chocolate Factory', 'James and the Giant Peach'],
    voiceCharacteristics: ['invented words', 'conspiratorial whisper to the reader', 'surprising reversals', 'absurdist detail'],
    avoidances: ['adult political commentary', 'sentimentality', 'passive protagonists'],
    sampleTone: 'A secret shared between you and the child hero — giddy, sharp-eyed, triumphant.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'maya_angelou',
    name: 'Maya Angelou',
    description: 'Rhythmic, soulful, unflinching resilience',
    persona: 'The Testifying Voice',
    era: '1928–2014',
    majorWorks: ["I Know Why the Caged Bird Sings", 'Still I Rise', 'Mom & Me & Mom'],
    voiceCharacteristics: ['musical cadence', 'sensory richness', 'dignity in adversity', 'communal voice'],
    avoidances: ['detached narration', 'irony without warmth', 'passive constructions'],
    sampleTone: 'Rooted as an oak, open as sky — bearing witness, claiming joy.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'vikram_seth',
    name: 'Vikram Seth',
    description: 'Elegant, precise, deeply humanistic',
    persona: 'The Careful Chronicler',
    era: '1952–present',
    majorWorks: ['A Suitable Boy', 'The Golden Gate', 'Two Lives'],
    voiceCharacteristics: ['careful observation', 'emotional restraint', 'precise vocabulary', 'multicultural empathy'],
    avoidances: ['overwrought emotion', 'dialect caricature', 'rushed conclusions'],
    sampleTone: 'Patient as a miniaturist — each detail chosen, each feeling earned.',
    ageAlignment: ['teen'],
  },
  {
    id: 'arundhati_roy',
    name: 'Arundhati Roy',
    description: 'Dense sensory prose, political passion, layered time',
    persona: 'The Weaver of Worlds',
    era: '1961–present',
    majorWorks: ['The God of Small Things', 'The Ministry of Utmost Happiness', 'Capitalism: A Ghost Story'],
    voiceCharacteristics: ['fragmented chronology', 'visceral imagery', 'political conscience', 'invented compound words'],
    avoidances: ['simple linear narrative', 'uncomplicated heroes', 'sanitised settings'],
    sampleTone: 'Rich and restless — like monsoon air before the rain breaks.',
    ageAlignment: ['teen'],
  },
  {
    id: 'rk_narayan',
    name: 'R.K. Narayan',
    description: 'Gentle irony, small-town India, everyday epiphanies',
    persona: 'The Malgudi Chronicler',
    era: '1906–2001',
    majorWorks: ['Swami and Friends', 'The Guide', 'Malgudi Days'],
    voiceCharacteristics: ['light irony', 'unheroic heroes', 'dialogue-driven scenes', 'timeless small-town texture'],
    avoidances: ['grand historical sweep', 'melodrama', 'moralistic endings'],
    sampleTone: 'Quiet as an afternoon in a sleepy town — wry, fond, accepting.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'premchand',
    name: 'Premchand',
    description: 'Social realism, rural India, moral urgency',
    persona: 'The Voice of the Soil',
    era: '1880–1936',
    majorWorks: ['Godaan', 'Nirmala', 'Idgah'],
    voiceCharacteristics: ['vivid rural settings', 'class consciousness', 'moral clarity', 'compassion for the marginalised'],
    avoidances: ['urban sophistication', 'ambiguous morality', 'ornate language'],
    sampleTone: 'Direct as ploughed earth — honest, compassionate, unsparing.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'mark_twain',
    name: 'Mark Twain',
    description: 'Satirical wit, vernacular warmth, American adventure',
    persona: 'The Mississippi Rascal',
    era: '1835–1910',
    majorWorks: ['The Adventures of Tom Sawyer', 'Adventures of Huckleberry Finn', 'The Prince and the Pauper'],
    voiceCharacteristics: ['tall tales', 'colloquial rhythm', 'sharp social satire wrapped in humour', 'boy-hero perspective'],
    avoidances: ['phonetic dialect spelling', 'cynicism without affection', 'adult political lectures'],
    sampleTone: 'One eye winking at authority, the other watching the river — free, funny, sly.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'charles_dickens',
    name: 'Charles Dickens',
    description: 'Vivid characters, social conscience, Victorian drama',
    persona: 'The Great Chronicler',
    era: '1812–1870',
    majorWorks: ['Oliver Twist', 'A Tale of Two Cities', 'Great Expectations'],
    voiceCharacteristics: ['theatrical character introductions', 'serialised dramatic beats', 'sharp class observation', 'redemption arcs'],
    avoidances: ['modern slang', 'ambiguous villains', 'flat secondary characters'],
    sampleTone: 'Grand as a fog-lit city — generous, indignant, full of life.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'jane_austen',
    name: 'Jane Austen',
    description: 'Ironic observation, social comedy, inner life',
    persona: 'The Witty Observer',
    era: '1775–1817',
    majorWorks: ['Pride and Prejudice', 'Sense and Sensibility', 'Emma'],
    voiceCharacteristics: ['free indirect discourse', 'dry social irony', 'precise emotional observation', 'wit without cruelty'],
    avoidances: ['explicit moralising', 'melodrama', 'physical action scenes'],
    sampleTone: 'Polished as a drawing-room mirror — seeing everything, saying it sidelong.',
    ageAlignment: ['teen'],
  },
  {
    id: 'leo_tolstoy',
    name: 'Leo Tolstoy',
    description: 'Moral depth, psychological realism, epic scope',
    persona: 'The Moral Giant',
    era: '1828–1910',
    majorWorks: ['War and Peace', 'Anna Karenina', 'The Death of Ivan Ilyich'],
    voiceCharacteristics: ['long internal monologue', 'moral wrestling', 'historical panorama', 'simple peasant wisdom contrasted with noble complexity'],
    avoidances: ['irony', 'ambiguous ethics', 'rapid-fire plot'],
    sampleTone: 'Slow and searching as a Russian winter — vast, honest, inevitable.',
    ageAlignment: ['teen'],
  },
  {
    id: 'gabriel_garcia_marquez',
    name: 'Gabriel García Márquez',
    description: 'Magical realism, Latin American heat, myth and memory',
    persona: 'The Dream Weaver',
    era: '1927–2014',
    majorWorks: ['One Hundred Years of Solitude', 'Love in the Time of Cholera', 'Chronicle of a Death Foretold'],
    voiceCharacteristics: ['matter-of-fact magical events', 'circular time', 'village as cosmos', 'lush tropical imagery'],
    avoidances: ['cold rationalism', 'linear causality', 'clinical description'],
    sampleTone: 'Where the ordinary turns into miracle without apology — warm, strange, timeless.',
    ageAlignment: ['teen'],
  },
  {
    id: 'paulo_coelho',
    name: 'Paulo Coelho',
    description: 'Allegorical simplicity, spiritual quest, universal wisdom',
    persona: 'The Pilgrim',
    era: '1947–present',
    majorWorks: ['The Alchemist', 'The Pilgrimage', 'Brida'],
    voiceCharacteristics: ['short parable-like paragraphs', 'universal archetypes', 'spiritual journey structure', 'simple but resonant aphorisms'],
    avoidances: ['irony', 'complex subplot', 'ambiguous spiritual messages'],
    sampleTone: 'Plain as a desert path — each step a lesson, each stone a sign.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'chimamanda_adichie',
    name: 'Chimamanda Ngozi Adichie',
    description: 'Nigerian voice, feminist clarity, cultural duality',
    persona: 'The Double-Vision Teller',
    era: '1977–present',
    majorWorks: ['Purple Hibiscus', 'Half of a Yellow Sun', 'Americanah'],
    voiceCharacteristics: ['bicultural perspective', 'precise emotional intelligence', 'political without preaching', 'sensory Nigerian detail'],
    avoidances: ['Western-centric framing', 'passive female characters', 'pat resolutions'],
    sampleTone: 'Clear as harmattan light — honest, layered, refusing easy answers.',
    ageAlignment: ['teen'],
  },
  {
    id: 'jules_verne',
    name: 'Jules Verne',
    description: 'Scientific adventure, wonder, meticulous invention',
    persona: 'The Adventurous Engineer',
    era: '1828–1905',
    majorWorks: ['Twenty Thousand Leagues Under the Sea', 'Around the World in Eighty Days', 'Journey to the Centre of the Earth'],
    voiceCharacteristics: ['detailed technical description', 'expedition pacing', 'enthusiastic encyclopaedic digressions', 'optimism about science'],
    avoidances: ['supernatural explanations', 'emotional interiority', 'ambiguous technology'],
    sampleTone: 'Brisk and inventive — every obstacle a puzzle, every horizon an invitation.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'hg_wells',
    name: 'H.G. Wells',
    description: 'Social prophecy, scientific imagination, everyday setting invaded by the extraordinary',
    persona: 'The Prophet-Scientist',
    era: '1866–1946',
    majorWorks: ['The Time Machine', 'The War of the Worlds', 'The Invisible Man'],
    voiceCharacteristics: ['matter-of-fact extraordinary events', 'social class critique', 'journalistic clarity', 'slow dread building'],
    avoidances: ['optimistic endings', 'escapist fantasy', 'individual heroism over systemic change'],
    sampleTone: 'Calm and unsettling — the extraordinary arriving in an ordinary street.',
    ageAlignment: ['middle', 'teen'],
  },
  {
    id: 'jk_rowling',
    name: 'J.K. Rowling',
    description: 'Magical world-building, chosen hero, moral clarity',
    persona: 'The World-Builder',
    era: '1965–present',
    majorWorks: ['Harry Potter series', 'The Ickabog', 'The Christmas Pig'],
    voiceCharacteristics: ['invented proper nouns', 'chapter-ending hooks', 'warmly ironic narrator', 'boarding-school social dynamics'],
    avoidances: ['grimdark tone', 'absence of humour', 'unresolved plot threads'],
    sampleTone: 'Cosy yet urgent — the common room fire and the dark forest, always together.',
    ageAlignment: ['young', 'middle'],
  },
  {
    id: 'toni_morrison',
    name: 'Toni Morrison',
    description: 'Lyrical power, Black American experience, ancestral memory',
    persona: 'The Memory Keeper',
    era: '1931–2019',
    majorWorks: ['Beloved', 'Song of Solomon', 'The Bluest Eye'],
    voiceCharacteristics: ['non-linear memory', 'communal voice', 'haunting imagery', 'dignity of suffering'],
    avoidances: ['linear chronology', 'simple resolution', 'distanced narration'],
    sampleTone: 'Deep as root memory — grieving, beautiful, insisting on humanity.',
    ageAlignment: ['teen'],
  },
  {
    id: 'khalil_gibran',
    name: 'Kahlil Gibran',
    description: 'Prophetic prose-poetry, spiritual universalism, Lebanese mysticism',
    persona: 'The Prophet Voice',
    era: '1883–1931',
    majorWorks: ['The Prophet', 'The Madman', 'Sand and Foam'],
    voiceCharacteristics: ['aphoristic wisdom', 'nature-as-metaphor', 'direct address to the reader', 'spiritual paradox'],
    avoidances: ['narrative plot', 'irony', 'grounded mundane detail'],
    sampleTone: 'A voice from a mountain — timeless, tender, speaking of what cannot be unsaid.',
    ageAlignment: ['middle', 'teen'],
  },
];

export const HINDI_AUTHOR_STYLES: HindiAuthorStyle[] = [
  {
    id: 'premchand_hindi',
    name: 'प्रेमचंद',
    description: 'सामाजिक यथार्थवाद, ग्रामीण भारत, नैतिक तात्कालिकता',
    persona: 'मिट्टी की आवाज़',
    era: '1880–1936',
    majorWorks: ['गोदान', 'निर्मला', 'ईदगाह'],
    voiceCharacteristics: ['सरल ग्रामीण भाषा', 'वर्ग-चेतना', 'नैतिक स्पष्टता', 'दलितों के प्रति करुणा'],
    avoidances: ['शहरी परिष्कार', 'अस्पष्ट नैतिकता', 'अलंकृत भाषा'],
    sampleTone: 'जुती हुई ज़मीन की तरह सीधी — ईमानदार, करुणामय, निर्भीक।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tadbhava',
  },
  {
    id: 'mahadevi_varma',
    name: 'महादेवी वर्मा',
    description: 'छायावादी काव्य-गद्य, स्त्री-चेतना, आध्यात्मिक करुणा',
    persona: 'आँसुओं की रानी',
    era: '1907–1987',
    majorWorks: ['मेरा परिवार', 'अतीत के चलचित्र', 'स्मृति की रेखाएँ'],
    voiceCharacteristics: ['संगीतात्मक वाक्य', 'प्रकृति-बिम्ब', 'स्त्री-जीवन की पीड़ा', 'आध्यात्मिक गहराई'],
    avoidances: ['तार्किक शुष्कता', 'हास्य', 'राजनीतिक टिप्पणी'],
    sampleTone: 'दीपक की लौ जैसी — कोमल, स्थिर, अंधेरे में भी जलती।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'harivansh_rai_bachchan',
    name: 'हरिवंश राय बच्चन',
    description: 'मधुशाला की लय, जीवन-दर्शन, सरल गेयता',
    persona: 'जीवन-गायक',
    era: '1907–2003',
    majorWorks: ['मधुशाला', 'मधुबाला', 'क्या भूलूँ क्या याद करूँ'],
    voiceCharacteristics: ['गेय लय', 'जीवन-दर्शन', 'सरल प्रतीक', 'उत्सव-भाव'],
    avoidances: ['क्लिष्ट संस्कृत पद', 'निराशावाद', 'राजनीतिक व्याख्या'],
    sampleTone: 'मदिरालय की शाम जैसी — उत्सवी, दार्शनिक, मानवीय।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tadbhava',
  },
  {
    id: 'gulzar',
    name: 'गुलज़ार',
    description: 'उर्दू-हिंदी मिश्रण, बिम्बात्मक काव्य, शहरी उदासी',
    persona: 'धुएँ का शायर',
    era: '1934–present',
    majorWorks: ['त्रिवेणी', 'रात पश्मीने की', 'पुखराज'],
    voiceCharacteristics: ['उर्दू-हिंदी मिश्रण', 'अप्रत्याशित बिम्ब', 'मौन का सौंदर्य', 'शहरी एकाकीपन'],
    avoidances: ['ग्रामीण परिदृश्य', 'नैतिक उपदेश', 'उज्ज्वल समाधान'],
    sampleTone: 'धुएँ में लिखी इबारत — अधूरी, खूबसूरत, बेहद असरदार।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'mixed-urdu',
  },
  {
    id: 'nirala',
    name: 'सूर्यकांत त्रिपाठी निराला',
    description: 'छायावादी विद्रोह, श्रमिक-गरिमा, छंदमुक्त ओज',
    persona: 'महाप्राण',
    era: '1896–1961',
    majorWorks: ['राम की शक्तिपूजा', 'सरोज स्मृति', 'कुकुरमुत्ता'],
    voiceCharacteristics: ['ओजपूर्ण भाषा', 'विद्रोही स्वर', 'श्रमिक-प्रतीक', 'छंदमुक्त प्रवाह'],
    avoidances: ['कोमल स्वर', 'समझौतापरस्त नैतिकता', 'शहरी परिष्कार'],
    sampleTone: 'तूफ़ान में खड़े वट-वृक्ष जैसी — अडिग, ओजस्वी, स्वतंत्र।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'jaishankar_prasad',
    name: 'जयशंकर प्रसाद',
    description: 'छायावाद, भारतीय इतिहास-दर्शन, गीतात्मकता',
    persona: 'युग-दृष्टा',
    era: '1889–1937',
    majorWorks: ['कामायनी', 'चंद्रगुप्त', 'स्कंदगुप्त'],
    voiceCharacteristics: ['भव्य ऐतिहासिक परिदृश्य', 'प्रतीकात्मक पात्र', 'दार्शनिक गहराई', 'संस्कृत-निष्ठ भाषा'],
    avoidances: ['आधुनिक बोलचाल', 'हास्य', 'व्यक्तिगत आत्मकथा'],
    sampleTone: 'महाकाव्य की तरह भव्य — इतिहास और स्वप्न एक साथ।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'sumitranandan_pant',
    name: 'सुमित्रानंदन पंत',
    description: 'प्रकृति-प्रेम, सौंदर्यवाद, प्रगतिशील चेतना',
    persona: 'प्रकृति का कवि',
    era: '1900–1977',
    majorWorks: ['पल्लव', 'चिदम्बरा', 'लोकायतन'],
    voiceCharacteristics: ['प्रकृति-बिम्ब', 'कोमल संगीत', 'सौंदर्य-दृष्टि', 'मानवतावादी आदर्श'],
    avoidances: ['कटु यथार्थ', 'शहरी चित्रण', 'राजनीतिक आग्रह'],
    sampleTone: 'हिमालय की कोख में जन्मे झरने जैसी — निर्मल, सुरीली, स्वतंत्र।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'dharamvir_bharati',
    name: 'धर्मवीर भारती',
    description: 'प्रेम, संघर्ष, आधुनिक बोध',
    persona: 'आधुनिक संवेदना',
    era: '1926–1997',
    majorWorks: ['गुनाहों का देवता', 'सूरज का सातवाँ घोड़ा', 'अंधा युग'],
    voiceCharacteristics: ['भावुक गद्य', 'प्रेम-त्रिकोण', 'आधुनिक युवा-चेतना', 'पौराणिक संदर्भ'],
    avoidances: ['शुष्क तार्किकता', 'ग्रामीण परिवेश', 'उपदेशात्मक स्वर'],
    sampleTone: 'दिल की बात सीधे कहना — भावुक, ईमानदार, यादगार।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'modern',
  },
  {
    id: 'amrita_pritam',
    name: 'अमृता प्रीतम',
    description: 'पंजाबी-हिंदी दर्द, स्त्री-स्वतंत्रता, विभाजन-स्मृति',
    persona: 'दर्द की गवाह',
    era: '1919–2005',
    majorWorks: ['पिंजर', 'रसीदी टिकट', 'एक थी आनंदी'],
    voiceCharacteristics: ['साहसिक स्त्री-दृष्टि', 'विभाजन-पीड़ा', 'प्रेम और विद्रोह', 'सीधी भाषा'],
    avoidances: ['मर्द-केंद्रित नज़रिया', 'सुखद समाधान', 'औपचारिक भाषा'],
    sampleTone: 'खुली हवा में कहा गया सच — निर्भीक, दर्दनाक, सुंदर।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'tadbhava',
  },
  {
    id: 'phanishwarnath_renu',
    name: 'फणीश्वरनाथ रेणु',
    description: 'आंचलिक यथार्थ, बिहारी लोक-जीवन, ग्रामीण संगीत',
    persona: 'आँचल का कवि',
    era: '1921–1977',
    majorWorks: ['मैला आँचल', 'परती परिकथा', 'ठुमरी'],
    voiceCharacteristics: ['आंचलिक बोली के रंग', 'लोकगीत-तत्व', 'किसान-जीवन की जटिलता', 'बहुपात्री आख्यान'],
    avoidances: ['शहरी मध्यवर्गीय दृष्टि', 'सरलीकृत समाधान', 'एकल नायक'],
    sampleTone: 'मिट्टी और मेले की महक — जीवंत, बहुरंगी, अपना।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tadbhava',
  },
  {
    id: 'hazari_prasad_dwivedi',
    name: 'हज़ारीप्रसाद द्विवेदी',
    description: 'ललित निबंध, भारतीय संस्कृति, विद्वत्तापूर्ण सरसता',
    persona: 'विद्वान-लालित्य',
    era: '1907–1979',
    majorWorks: ['अशोक के फूल', 'कल्पलता', 'बाणभट्ट की आत्मकथा'],
    voiceCharacteristics: ['ललित निबंध-शैली', 'भारतीय दर्शन के संदर्भ', 'हल्की विनोदवृत्ति', 'इतिहास-सजीव करना'],
    avoidances: ['शुष्क शोधपत्र-शैली', 'राजनीतिक पक्षधरता', 'तनावपूर्ण कथानक'],
    sampleTone: 'पुरानी पोथी और आम के बौर की खुशबू — विद्वान, सरस, भारतीय।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'ismat_chughtai',
    name: 'इस्मत चुगताई',
    description: 'स्त्री-यथार्थ, उर्दू व्यंग्य, मध्यवर्गीय घर की कहानी',
    persona: 'बेबाक बेगम',
    era: '1915–1991',
    majorWorks: ['लिहाफ', 'टेढ़ी लकीर', 'जिद्दी'],
    voiceCharacteristics: ['व्यंग्यात्मक तीक्ष्णता', 'स्त्री-शरीर की राजनीति', 'मध्यवर्गीय पाखंड की आलोचना', 'बोलचाल की उर्दू'],
    avoidances: ['रूमानी आदर्शवाद', 'पुरुष-दृष्टि', 'सुखद अंत'],
    sampleTone: 'घर की दीवारों से बाहर झाँकती आँख — तीखी, साहसी, सच्ची।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'mixed-urdu',
  },
  {
    id: 'rahul_sankrityayan',
    name: 'राहुल सांकृत्यायन',
    description: 'यात्रा-वृत्तांत, तर्कशील बुद्धिवाद, बौद्ध-दर्शन',
    persona: 'महापंडित यायावर',
    era: '1893–1963',
    majorWorks: ['वोल्गा से गंगा', 'मेरी जीवन-यात्रा', 'दर्शन-दिग्दर्शन'],
    voiceCharacteristics: ['यात्रा-कथा शैली', 'तुलनात्मक दृष्टि', 'तर्कशील विश्लेषण', 'ऐतिहासिक विस्तार'],
    avoidances: ['अंधविश्वास', 'धर्म-केंद्रित आख्यान', 'भावुकता'],
    sampleTone: 'क्षितिज तक जाने वाले यायावर की डायरी — जिज्ञासु, तथ्यपरक, अदम्य।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'tatsama',
  },
  {
    id: 'nirmal_verma',
    name: 'निर्मल वर्मा',
    description: 'यूरोपीय एकाकीपन, अस्तित्ववाद, हिंदी आधुनिकता',
    persona: 'एकाकी यात्री',
    era: '1929–2005',
    majorWorks: ['परिंदे', 'वे दिन', 'लाल टीन की छत'],
    voiceCharacteristics: ['लंबे चिंतनशील वाक्य', 'यूरोपीय परिदृश्य', 'अस्तित्ववादी प्रश्न', 'मौन और स्मृति'],
    avoidances: ['सामाजिक आंदोलन', 'स्पष्ट नैतिकता', 'सुखद अंत'],
    sampleTone: 'प्राग की सर्दी में एकांत कमरे में — चिंतनशील, गहरी, उदासीन।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'modern',
  },
  {
    id: 'mannu_bhandari',
    name: 'मन्नू भंडारी',
    description: 'नई कहानी, स्त्री-मध्यवर्ग, आंतरिक द्वंद्व',
    persona: 'अंतर्मन की आवाज़',
    era: '1931–2021',
    majorWorks: ['आपका बंटी', 'महाभोज', 'एक प्लेट सैलाब'],
    voiceCharacteristics: ['स्त्री की आंतरिक आवाज़', 'परिवार के भीतर संघर्ष', 'मध्यवर्गीय यथार्थ', 'संवेदनशील शैली'],
    avoidances: ['आदर्शवादी समाधान', 'वीर-पुरुष केंद्रित आख्यान', 'ऐतिहासिक महाकाव्य'],
    sampleTone: 'घर के अंदर से देखा सच — कोमल, ईमानदार, बेचैन।',
    ageAlignment: ['teen'],
    vocabularyRegister: 'modern',
  },
  {
    id: 'vishnu_prabhakar',
    name: 'विष्णु प्रभाकर',
    description: 'गाँधीवादी मूल्य, जीवनी, सामाजिक सेवा-भाव',
    persona: 'सेवा-पथ का राही',
    era: '1912–2009',
    majorWorks: ['आवारा मसीहा', 'अर्धनारीश्वर', 'धरती अब भी घूम रही है'],
    voiceCharacteristics: ['गाँधीवादी सादगी', 'सत्याग्रह की भाषा', 'नैतिक आग्रह', 'जीवनी-शैली'],
    avoidances: ['हिंसा का महिमामंडन', 'जटिल मनोविज्ञान', 'शहरी पाखंड'],
    sampleTone: 'चरखे की लय जैसी — धीमी, नैतिक, अडिग।',
    ageAlignment: ['middle', 'teen'],
    vocabularyRegister: 'tadbhava',
  },
  {
    id: 'surdas',
    name: 'सूरदास',
    description: 'भक्ति-काव्य, बाल-कृष्ण, विनम्र भक्त-भाव',
    persona: 'अष्टछाप का भक्त',
    era: '1478–1583',
    majorWorks: ['सूरसागर', 'सूर-सारावली', 'साहित्य-लहरी'],
    voiceCharacteristics: ['बालक कृष्ण की लीलाएँ', 'माता यशोदा की ममता', 'भक्ति-भाव', 'ब्रजभाषा की मधुरता'],
    avoidances: ['दार्शनिक शुष्कता', 'राजनीतिक टिप्पणी', 'वियोग-शृंगार'],
    sampleTone: 'गोकुल की धूल और नन्दलाल की किलकारी — भक्त का प्रेम, बाल का उल्लास।',
    ageAlignment: ['young', 'middle'],
    vocabularyRegister: 'avadhi',
  },
  {
    id: 'kabir',
    name: 'कबीर',
    description: 'निर्गुण दोहे, सामाजिक क्रांति, सीधी बात',
    persona: 'जुलाहे का साधु',
    era: '1440–1518',
    majorWorks: ['बीजक', 'कबीर ग्रंथावली', 'साखी'],
    voiceCharacteristics: ['दो पंक्तियों में सत्य', 'धार्मिक पाखंड पर कड़ा व्यंग्य', 'सीधी बोलचाल', 'जाति-निरपेक्ष दृष्टि'],
    avoidances: ['जटिल शास्त्र-उद्धरण', 'बाहरी कर्मकाण्ड', 'लंबे वर्णन'],
    sampleTone: 'धागे की नोक पर रखा हीरा — छोटा, तीखा, युगों तक चमकता।',
    ageAlignment: ['young', 'middle', 'teen'],
    vocabularyRegister: 'tadbhava',
  },
];

export const SCIENCE_NARRATOR_STYLES: NarratorStyle[] = [
  {
    id: 'feynman',
    name: 'Richard Feynman',
    persona: 'The Curious Explainer',
    era: '1918–1988',
    description: 'Playful, childlike curiosity; strips away jargon; loves thought experiments',
    voiceCharacteristics: ['rhetorical questions', 'thought experiments', 'delight in not knowing', 'building from first principles'],
    avoidances: ['authority appeals', 'unexplained jargon', 'passive voice'],
    sampleTone: "Grinning in front of a blackboard — \"Isn't that wonderful? Let's figure it out together.\"",
    ageAlignment: ['young', 'middle', 'teen'],
    majorWorks: ["The Feynman Lectures on Physics", "Surely You're Joking, Mr. Feynman!", 'QED'],
  },
  {
    id: 'sagan',
    name: 'Carl Sagan',
    persona: 'The Cosmic Poet',
    era: '1934–1996',
    description: 'Grand cosmic scale, poetic awe, humanist perspective on science',
    voiceCharacteristics: ['cosmic scale shifts', 'poetic imagery', 'humanist urgency', 'billions and billions'],
    avoidances: ['cold reductionism', 'dismissal of wonder', 'technical-only framing'],
    sampleTone: 'Standing beneath a billion stars — filled with reverence, speaking of our pale blue dot.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['Cosmos', 'The Pale Blue Dot', 'Contact'],
  },
  {
    id: 'attenborough',
    name: 'David Attenborough',
    persona: 'The Patient Observer',
    era: '1926–present',
    description: 'Hushed reverence for nature, building drama from observation, long perspective',
    voiceCharacteristics: ['hushed pacing', 'building dramatic tension', 'evolutionary timescale', 'precise sensory observation'],
    avoidances: ['rushed explanation', 'anthropomorphism', 'abstract theory without grounding'],
    sampleTone: 'In a whisper, kneeling beside the extraordinary — patient, reverent, utterly precise.',
    ageAlignment: ['young', 'middle', 'teen'],
    majorWorks: ['Life on Earth', 'Planet Earth', 'A Life on Our Planet'],
  },
  {
    id: 'oliver_sacks',
    name: 'Oliver Sacks',
    persona: 'The Compassionate Neurologist',
    era: '1933–2015',
    description: 'Human stories at the centre of science, clinical empathy, case-study narrative',
    voiceCharacteristics: ['patient as hero', 'clinical empathy', 'unexpected connections', 'wonder at the brain'],
    avoidances: ['detached statistics', 'diagnosis without humanity', 'abstract theory without person'],
    sampleTone: 'Sitting with a patient — curious, moved, seeing the person inside the condition.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['The Man Who Mistook His Wife for a Hat', 'Awakenings', 'On the Move'],
  },
  {
    id: 'marie_curie_voice',
    name: 'Marie Curie',
    persona: 'The Determined Discoverer',
    era: '1867–1934',
    description: 'Methodical persistence, lab notebook precision, quiet revolutionary dignity',
    voiceCharacteristics: ['meticulous experimental detail', 'quiet perseverance', 'facts over fame', 'European formal elegance'],
    avoidances: ['self-promotion', 'speculation without evidence', 'dramatic overstatement'],
    sampleTone: 'Measured and exact — the glow of radium in a dark shed, recorded with steady hands.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['Radioactive: Marie & Pierre Curie', 'Research on Radioactive Substances'],
  },
  {
    id: 'stephen_hawking_voice',
    name: 'Stephen Hawking',
    persona: 'The Wit of the Cosmos',
    era: '1942–2018',
    description: 'Dry British wit, black holes made simple, defiant joy',
    voiceCharacteristics: ['dry wit', 'extreme complexity made elegant', 'defiant optimism', 'short declarative sentences'],
    avoidances: ['self-pity', 'unnecessary jargon', 'verbose hedging'],
    sampleTone: 'Deadpan in a wheelchair before the infinite — sharp, amused, absolutely serious.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['A Brief History of Time', 'The Universe in a Nutshell', 'Black Holes and Baby Universes'],
  },
];

export const PHILOSOPHY_NARRATOR_STYLES: NarratorStyle[] = [
  {
    id: 'alan_watts',
    name: 'Alan Watts',
    persona: 'The Zen Interpreter',
    era: '1915–1973',
    description: 'Eastern wisdom in Western words, playful paradox, anti-anxiety',
    voiceCharacteristics: ['playful paradox', 'Zen koans adapted for Western ears', 'anti-goal-orientation', 'laughter as insight'],
    avoidances: ['rigid definitions', 'academic citation', 'self-improvement tone'],
    sampleTone: 'Chuckling at the cosmic joke — relaxed, liberating, surprisingly wise.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['The Way of Zen', 'The Wisdom of Insecurity', 'Tao: The Watercourse Way'],
  },
  {
    id: 'bertrand_russell',
    name: 'Bertrand Russell',
    persona: 'The Clear Rationalist',
    era: '1872–1970',
    description: 'Crystal-clear logic, anti-dogmatism, dry wit, intellectual courage',
    voiceCharacteristics: ['clear logical structure', 'gentle demolition of received wisdom', 'dry humour', 'moral conviction'],
    avoidances: ['mysticism', 'undefined terms', 'authority appeals'],
    sampleTone: 'Precise as a proof — kind, firm, absolutely unwilling to pretend.',
    ageAlignment: ['teen'],
    majorWorks: ['The Problems of Philosophy', 'Why I Am Not a Christian', 'A History of Western Philosophy'],
  },
  {
    id: 'simone_de_beauvoir',
    name: 'Simone de Beauvoir',
    persona: 'The Existential Witness',
    era: '1908–1986',
    description: 'Feminist existentialism, freedom and responsibility, lived experience',
    voiceCharacteristics: ['first-person situated knowledge', 'freedom as burden and gift', 'gender as construction', 'existentialist urgency'],
    avoidances: ['abstract without personal', 'passive acceptance', 'biological determinism'],
    sampleTone: 'Standing at the crossroads of freedom — urgent, personal, demanding more.',
    ageAlignment: ['teen'],
    majorWorks: ['The Second Sex', 'The Ethics of Ambiguity', 'Memoirs of a Dutiful Daughter'],
  },
  {
    id: 'rumi_voice',
    name: 'Rumi',
    persona: 'The Whirling Mystic',
    era: '1207–1273',
    description: 'Sufi love poetry, divine longing, parable-as-philosophy',
    voiceCharacteristics: ['parable and metaphor', 'divine love as central force', 'reed flute of longing', 'whirling surrender'],
    avoidances: ['cold logic', 'political analysis', 'literal interpretation of sacred texts'],
    sampleTone: 'A candle burning toward its own flame — ecstatic, tender, eternally returning.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['Masnavi', 'Divan-e Shams', 'Fihi Ma Fihi'],
  },
  {
    id: 'aristotle_voice',
    name: 'Aristotle',
    persona: 'The Systematic Observer',
    era: '384–322 BCE',
    description: 'Categories and causes, virtue ethics, the good life defined through practice',
    voiceCharacteristics: ['systematic classification', 'practical wisdom (phronesis)', 'virtue as habit', 'nature as teacher'],
    avoidances: ['mystical leaps', 'individualist ethics', 'ahistorical abstraction'],
    sampleTone: 'Methodical as a naturalist cataloguing species — finding virtue in the middle path.',
    ageAlignment: ['middle', 'teen'],
    majorWorks: ['Nicomachean Ethics', 'Politics', 'Poetics'],
  },
  {
    id: 'gandhi_voice',
    name: 'Mahatma Gandhi',
    persona: 'The Moral Experimenter',
    era: '1869–1948',
    description: 'Satyagraha, non-violence as active power, self-experiment as proof',
    voiceCharacteristics: ['personal experiment as argument', 'moral clarity', 'non-violence as strength', 'simple living as philosophy'],
    avoidances: ['theoretical abstraction', 'violence glorification', 'cynicism about human nature'],
    sampleTone: 'Walking barefoot to the sea — each step a statement, each act a teaching.',
    ageAlignment: ['young', 'middle', 'teen'],
    majorWorks: ['The Story of My Experiments with Truth', 'Hind Swaraj', 'Satyagraha in South Africa'],
  },
];

export const DEFAULT_LANGUAGE = Language.ENGLISH;
